### ISSUE TITLE
HTTP/1.1 400 Bad Request

### ISSUE THREAD

**Issue by fohnbit** [rharder/jpushbullet2#7]
Hello,

I get since 2 days for each notification with "sendNoteAsync" the error

17:30:54.078 [Executor-for-net.iharder.jpushbullet2.PushbulletClient@6b34a61c] DEBUG n.i.jpushbullet2.PushbulletClient - HTTP/1.1 400 Bad Request

Is there something new on the PushBullet Server?

**Comment by rharder** [comment]
I'm not sure I'm understanding the problem.  Do you mean it takes two days
for your notifications to reach you?  -Rob

**Comment by fohnbit** [comment]
Hi,

no I mean then Pushbullet doesnt work ... did it as yours working?
Each message I send, I get the error:
17:30:54.078 [Executor-for-net.iharder.jpushbullet2.PushbulletClient@6b34a61] DEBUG n.i.jpushbullet2.PushbulletClient - **HTTP/1.1 400 Bad Request**

Can you please confirm that at yours the library work fine?
Here at me it works a long time ... then it stop working with the error above.

I´m using since a while Java 1.8 ... maybe this is the problem?

**Comment by rharder** [comment]
Mine does still work but I'm not sure what version of Java I'm using. I'll have to check later.

**Comment by fohnbit** [comment]
Oh, thats interesting. Don´t know why it first run fine and now not.

**Comment by fohnbit** [comment]
OK, I see now an error:
Error: net.iharder.jpushbullet2.PushbulletException: Pushbullet Pro is required to make this call.

So why this happen suddenly?

**Comment by fohnbit** [comment]
Oh, the free Acount is limitet to 100 Message per month.

Maybe this is the problem ... has to wait for the next month ... then I see if this is the problem

**Comment by rharder** [comment]
Bingo.  Good detective work.  I didn't know about that limit. -Rob
